require("afnan.plugins")
require("afnan.remaps")
require("afnan.treesitter")
require("afnan.lsp")
require("afnan.settings")
require("afnan.statusline")
require("afnan.autocommands")
require("afnan.disabled")
